apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-sc
  template:
    metadata:
      labels:
        app: data-exchange-sc
    spec:
      containers:
        - name: writer
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["while true; do echo $(date) >> /shared/data.txt; sleep 5; done"]
          volumeMounts:
            - name: sc-storage
              mountPath: /shared
        - name: reader
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["tail -f /shared/data.txt"]
          volumeMounts:
            - name: sc-storage
              mountPath: /shared
      volumes:
        - name: sc-storage
          persistentVolumeClaim:
            claimName: data-pvc-sc
