apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>ConfigMap Demo</title>
    </head>
    <body>
      <h1>Привет!</h1>
      <p>Эта страница загружена из ConfigMap</p>
    </body>
    </html>
